// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PriscilaZuniga_Examen1P.Migrations
{
    [DbContext(typeof(PriscilaZuniga_DBContext))]
    partial class PriscilaZuniga_DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PriscilaZuniga_Examen1P.Models.PZClass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<bool>("PZ_Activo")
                        .HasColumnType("bit");

                    b.Property<string>("PZ_Apodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PZ_FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PZ_Peso")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("PZClass");
                });
#pragma warning restore 612, 618
        }
    }
}
